### PR TITLE
Update Mermaid to 10.2.1 and fix mermaid.init() call

### PR DESCRIPTION
**Pull request by martinschilliger**
This PR addresses or contains:
* Fixed loading with Mermaid 9.3.0
* Inserted random function instead of relying on Date().getTime()
* removed unused config reading

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

Overtakes https://github.com/SemanticMediaWiki/Mermaid/pull/94

### CODE REVIEW

**Comment by gesinn-it-gea** [comment]
for reference: mermaid-js RELEASE NOTES for 9.0.0 https://github.com/mermaid-js/mermaid/releases/tag/9.0.0

**Review by martinschilliger — COMMENTED** [review]
Update to 10.2.1

**Comment by antibarbie** [comment]
I tested your branch against mediawiki 1.35 ; and ... with 10.2.1 (also with others 10.x) firefox chokes on "SyntaxError: function statement requires a name" ; couldn't spot the exact problem on minified javascript, but the 10.x.x versions all seems to have the same symptoms.

When editing your package.json to go back to 9.4.3 it runs fine.

**Comment by sneakers-the-rat** [comment]
@antibarbie the problem you're getting is probably from how the mediawiki resourceloader minifies everything, including already-minified vendored packages like this one. There is an install script that adds a `/*@nomin*/` tag to the top of the file when you install it via composer, but that wouldn't get triggered if you just cloned it from git. added it manually in https://github.com/SemanticMediaWiki/Mermaid/pull/102 , which works from a clone.

**Comment by martinschilliger** [comment]
TBH right now I don't understand, if I could or should do anything else. Is there something needed from my side?

**Comment by martinschilliger** [comment]
Ah, already surpassed: https://github.com/SemanticMediaWiki/Mermaid/pull/102
Closing this one.

**Pull request closed without merging**
