### PR TITLE
Add flowchart useMaxWidth config parameter

### PR DESCRIPTION
**Pull request by cicalese**
This PR is made in reference to: #40

This PR addresses adds support for the flowchart useMaxWidth config parameter. It is activated by passing in 'config.flowchart.useMaxWidth=false' to the #mermaid parser function invocation, similar to the current 'config.theme=forest' and 'config.flowchart.curve=basis' parameters.

Scrollbars can be added to the area, if desired, with the following CSS in MediaWiki:Common.css (or elsewhere):
```css
.ext-mermaid > div {
	overflow: scroll;
}
```
In adding the new parameter, the configuration parameter parsing code was also refactored to make it easier to add additional configuration parameters in the future. Also, white space around the equals sign in the parameter was trimmed.

This PR includes:
- [x] Tests (unit/integration)
- [ ] CI build passed

Fixes #

### CODE REVIEW

**Comment by kghbln** [comment]
@cicalese Thanks a ton for the full. @mwjames and @JeroenDeDauw It will be cool to have a peep at this which would result into Mermaid 2.2.0 :)

**Comment by mwjames** [comment]
> @cicalese Thanks a ton for the full. @mwjames and @JeroenDeDauw It will be
> cool to have a peep at this which would result into Mermaid 2.2.0 :)

I have very limited time to review changes before 2020, so if you
think those changes are reasonable crafted then please merge at your
own discretion.

**Comment by JeroenDeDauw** [comment]
That's unfortunate. I had a look at this yesterday and concluded I cannot understand this code without investing a bunch of time.

**Comment by cicalese** [comment]
I have added an example to the sandbox at https://sandbox.semantic-mediawiki.org/wiki/Wide_Mermaid_Graph. If the patch is applied to the sandbox, you will see the difference in the behavior. You can see the same example with the patch applied at https://wikifarm.wmflabs.org/cpt/index.php/User:Ccicalese/Wide_Mermaid_Graph.

You can see an example of a large graph that currently benefits from the patch at https://wikifarm.wmflabs.org/cpt/index.php/Graph_Active_CPT_Tasks_by_Initiative?initiative=MCR (although this graph may change in the future if the source task data being graphed changes). Before the patch was applied, this graph was scaled down so much it was unreadable.

Note that this pull request also adds two tests.

**Comment by kghbln** [comment]
> I have very limited time to review changes before 2020, so if you
think those changes are reasonable crafted then please merge at your
own discretion.

We have a test passing, the test instance does not blow: I am now merging this. I sandbox does not blow withing the next week I will even do a release to get this improvement to the general public.

**Comment by kghbln** [comment]
@cicalese Thanks for your effort and the pull!

**Comment by cicalese** [comment]
Thank you, @kghbln!

**Comment by samwilson** [comment]
This is great!

Could a new release please be tagged?

**Comment by kghbln** [comment]
> Could a new release please be tagged?

No, there currently so many issues from upstream (MediaWiki) that I frankly lost the overview of things. When it comes to this extension this nonsense will have to be resolved:  https://github.com/SemanticMediaWiki/Mermaid/issues/21

I expect the next realest to be done somewhere in the second quarter 2020. Sorry but I am on my own here and moreover I am not a PHP developer.

**Pull request merged**
