### PR TITLE
Improve ID entropy, refs #12

### LINKED ISSUE #12: Multiple diagrams per page do not render
### Setup and configuration

- Mermaid version: 1.0.0
- MediaWiki version: 1.30
- PHP version: 7.1.14 (Windows binaries)
- Database system (MySQL, PostgresQL, etc.) and version: SQLite

### Issue

When `{{#mermaid:***}}` function is used multiple times on one page, only the first diagram is generated, the others not.

```
{{#mermaid:graph LR
Prague --> {{!}}travel by train{{!}}Brno
}}
{{#mermaid:graph LR
Prague --> {{!}}travel by bus{{!}}Brno
}}
{{#mermaid:graph LR
Prague --> {{!}}travel by car{{!}}Brno
}}
```

_...generates this output..._

image

### Reason
DIV elements are assigned the same ID, and thus it fails for the other elements.

image

### PR DESCRIPTION
**Pull request by mwjames**
Fixes #12

### CODE REVIEW

**Comment by mwjames** [comment]
> ...PHP Fatal error:  Call to undefined function Mermaid\random_int() in /home/travis/build/SemanticMediaWiki/mw/extensions/Mermaid/src/MermaidParserFunction.php on line 56

`random_int` only exists since PHP 7

**Comment by mwjames** [comment]
@kghbln If it weren't for the tests, I would have totally missed that.

**Comment by kghbln** [comment]
@mwjames No need to convince me. I am with you. :) Should I move this out to the public next week as 1.0.1?

**Comment by mwjames** [comment]
> Should I move this out to the public next week as 1.0.1?

Fine with me.

**Comment by foretix** [comment]
I made a test with 335dc87 commit and it works fine.

Thank you both for support.

**Pull request merged**
