### PR TITLE
Use Mermaid 8.0.0

### PR DESCRIPTION
**Pull request by mwjames**
refs #23

### CODE REVIEW

**Comment by kghbln** [comment]
What's what I call swift. I was just out for a wee and things are already in the making. Truly amazing.

**Comment by kghbln** [comment]
@mwjames Is this ready to be merged?

**Comment by kghbln** [comment]
@mwjames Any obstacles to merge and do a 2.0.0?

**Comment by mwjames** [comment]
Sorry for the delay (out of sight, out of mind).

>@mwjames Any obstacles to merge and do a 2.0.0?

Not from my side.

**Comment by kghbln** [comment]
> Sorry for the delay (out of sight, out of mind).

No worries. Things like this happen when one has to fight on multiple front-lines.

I guess you may do the honour of merging and I to the rest this week. :)

**Pull request merged**
