### PR TITLE
Fix "the the" typo in file dagre-d3.min.js

### PR DESCRIPTION
**Pull request by zoranzoki21**

### CODE REVIEW

**Comment by mwjames** [comment]
While I see no problem to merge this changes, you have to be aware that those are come from upstream meaning that as soon as we fetch a new version from upstream (such as D3) it is most likely that those issues persists as long as those aren't fixed in the original repository.

**Comment by zoranzoki21** [comment]
Should I close this PR than?

**Comment by kghbln** [comment]
> Should I close this PR than?

No not necessarily, you will just have to create another one upstream.

**Comment by zoranzoki21** [comment]
I did not understand quite well.

**Comment by kghbln** [comment]
> I did not understand quite well.

In order to prevent this pull from being completely useless you also need to create another pull for the upstream library.

**Comment by zoranzoki21** [comment]
> you also need to create another pull for the upstream library.

In which repository?

**Comment by kghbln** [comment]
> In which repository?

https://www.google.com/search?q=d3+library&gws_rd=ssl --> https://github.com/d3/d3

**Comment by zoranzoki21** [comment]
I can't find nothing there.

**Comment by kghbln** [comment]
> I can't find nothing there.

If you do not find the typo in the lib they may as well have fixed it in the meantime. This also means that it is not necessary to fix the typo here since the next time the lib is pulled in the fix will be pulled in too. :)

**Pull request closed without merging**
